# BMAD Pipeline Glue — retargets PR to epic branch and converts draft to ready.
# This is a plain GitHub Actions workflow (NOT gh-aw). Copy to .github/workflows/.
name: BMAD Pipeline Glue

on:
  pull_request:
    types: [labeled]

jobs:
  activate-story-pr:
    if: github.event.label.name == 'bmad-dev-ready'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Retarget PR and convert to ready
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          # Find epic-N label on the PR
          EPIC_LABEL=$(gh pr view "$PR_NUMBER" --repo "$REPO" \
            --json labels --jq '[.labels[].name | select(startswith("epic-"))] | first // empty')
          if [ -n "$EPIC_LABEL" ]; then
            EPIC_NUM="${EPIC_LABEL#epic-}"

            # Find the matching epic branch
            EPIC_BRANCH=$(gh api "repos/${REPO}/branches" --jq \
              "[.[].name | select(startswith(\"epic-${EPIC_NUM}-\"))] | first // empty")
            if [ -n "$EPIC_BRANCH" ]; then
              CURRENT_BASE=$(gh pr view "$PR_NUMBER" --repo "$REPO" \
                --json baseRefName --jq '.baseRefName')
              if [ "$CURRENT_BASE" != "$EPIC_BRANCH" ]; then
                echo "Retargeting PR #${PR_NUMBER}: ${CURRENT_BASE} → ${EPIC_BRANCH}"
                gh pr edit "$PR_NUMBER" --repo "$REPO" --base "$EPIC_BRANCH"
              fi
            fi
          fi

          # Convert draft to ready-for-review (triggers Dev Story)
          IS_DRAFT=$(gh pr view "$PR_NUMBER" --repo "$REPO" \
            --json isDraft --jq '.isDraft')
          if [ "$IS_DRAFT" = "true" ]; then
            echo "Converting PR #${PR_NUMBER} from draft to ready"
            gh pr ready "$PR_NUMBER" --repo "$REPO"
          fi
